theme = "catppuccin_macchiato"

[editor]
cursorline = true
cursorcolumn = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""

